variant = "loose"

[[issues]]
file = "src/Abstract/AbstractMessage.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/Abstract/AbstractMessage.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 1

[[issues]]
file = "src/Abstract/AbstractMessage.php"
code = "no-empty"
message = "Use of the `empty` construct."
count = 1

[[issues]]
file = "src/Abstract/AbstractMessage.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 2

[[issues]]
file = "src/Abstract/AbstractMessage.php"
code = "strict-behavior"
message = "Call to `in_array` must enforce strict comparison."
count = 1

[[issues]]
file = "src/Abstract/AbstractMessage.php"
code = "too-many-methods"
message = "Class has too many methods."
count = 1

[[issues]]
file = "src/Emitter/ResponseEmitter.php"
code = "literal-named-argument"
message = "Literal argument `' '` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/Emitter/ResponseEmitter.php"
code = "literal-named-argument"
message = "Literal argument `'-'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/Emitter/ResponseEmitter.php"
code = "literal-named-argument"
message = "Literal argument `false` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/Emitter/ResponseEmitter.php"
code = "literal-named-argument"
message = "Literal argument `true` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "halstead"
message = "Method has a high halstead effort"
count = 1

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "kan-defect"
message = "Class has a high kan defect score."
count = 1

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "literal-named-argument"
message = "Literal argument `''` should be passed as a named argument for clarity."
count = 2

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "literal-named-argument"
message = "Literal argument `'-'` should be passed as a named argument for clarity."
count = 2

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "literal-named-argument"
message = "Literal argument `'r'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "literal-named-argument"
message = "Literal argument `2` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "literal-named-argument"
message = "Literal argument `512` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "literal-named-argument"
message = "Literal argument `5` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "literal-named-argument"
message = "Literal argument `true` should be passed as a named argument for clarity."
count = 3

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 2

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "no-else-clause"
message = "Avoid `elseif` clauses."
count = 5

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "no-empty"
message = "Use of the `empty` construct."
count = 2

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 6

[[issues]]
file = "src/Factory/StreamFactory.php"
code = "literal-named-argument"
message = "Literal argument `'r+'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/Factory/StreamFactory.php"
code = "literal-named-argument"
message = "Literal argument `0` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/Factory/UploadedFileFactory.php"
code = "literal-named-argument"
message = "Literal argument `'waffle_upload_factory'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/Factory/UploadedFileFactory.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 1

[[issues]]
file = "src/Request.php"
code = "no-boolean-flag-parameter"
message = "Avoid boolean flag parameters."
count = 1

[[issues]]
file = "src/Request.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 1

[[issues]]
file = "src/Response.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/Response.php"
code = "literal-named-argument"
message = "Literal argument `'r+'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/Response.php"
code = "literal-named-argument"
message = "Literal argument `0` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/ServerRequest.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/ServerRequest.php"
code = "excessive-parameter-list"
message = "Parameter list is too long."
count = 1

[[issues]]
file = "src/ServerRequest.php"
code = "literal-named-argument"
message = "Literal argument `'r+'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/ServerRequest.php"
code = "literal-named-argument"
message = "Literal argument `0` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/ServerRequest.php"
code = "no-boolean-flag-parameter"
message = "Avoid boolean flag parameters."
count = 1

[[issues]]
file = "src/ServerRequest.php"
code = "too-many-methods"
message = "Class has too many methods."
count = 1

[[issues]]
file = "src/Stream.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/Stream.php"
code = "kan-defect"
message = "Class has a high kan defect score."
count = 1

[[issues]]
file = "src/Stream.php"
code = "literal-named-argument"
message = "Literal argument `true` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/Stream.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 1

[[issues]]
file = "src/Stream.php"
code = "no-else-clause"
message = "Avoid `elseif` clauses."
count = 1

[[issues]]
file = "src/Stream.php"
code = "no-error-control-operator"
message = "Unsafe use of error control operator `@`."
count = 1

[[issues]]
file = "src/Stream.php"
code = "too-many-methods"
message = "Class has too many methods."
count = 1

[[issues]]
file = "src/UploadedFile.php"
code = "literal-named-argument"
message = "Literal argument `'r'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/UploadedFile.php"
code = "literal-named-argument"
message = "Literal argument `true` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/UploadedFile.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 1

[[issues]]
file = "src/Uri.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/Uri.php"
code = "halstead"
message = "Method has a high halstead difficulty"
count = 1

[[issues]]
file = "src/Uri.php"
code = "literal-named-argument"
message = "Literal argument `'#'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/Uri.php"
code = "literal-named-argument"
message = "Literal argument `'/'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/Uri.php"
code = "literal-named-argument"
message = "Literal argument `'?'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/Uri.php"
code = "no-else-clause"
message = "Avoid `elseif` clauses."
count = 1

[[issues]]
file = "src/Uri.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 8

[[issues]]
file = "src/Uri.php"
code = "readable-literal"
message = "Numeric literal could use underscore separators for readability."
count = 1

[[issues]]
file = "src/Uri.php"
code = "too-many-methods"
message = "Class has too many methods."
count = 1

[[issues]]
file = "tests/src/Abstract/AbstractMessageTest.php"
code = "literal-named-argument"
message = "Literal argument `'r+'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/Abstract/AbstractMessageTest.php"
code = "too-many-methods"
message = "Class has too many methods."
count = 1

[[issues]]
file = "tests/src/AbstractTestCase.php"
code = "literal-named-argument"
message = "Literal argument `'r+'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/Emitter/ResponseEmitterTest.php"
code = "no-boolean-flag-parameter"
message = "Avoid boolean flag parameters."
count = 1

[[issues]]
file = "tests/src/Emitter/ResponseEmitterTest.php"
code = "no-global"
message = "Unsafe use of `global` keyword."
count = 3

[[issues]]
file = "tests/src/Factory/GlobalsFactoryTest.php"
code = "no-redundant-use"
message = "Unused import: `UploadedFile`."
count = 1

[[issues]]
file = "tests/src/Factory/GlobalsFactoryTest.php"
code = "prefer-static-closure"
message = "This arrow function does not use `$this` and should be declared static."
count = 1

[[issues]]
file = "tests/src/Factory/GlobalsFactoryTest.php"
code = "too-many-methods"
message = "Class has too many methods."
count = 1

[[issues]]
file = "tests/src/Factory/Psr17FactoryTest.php"
code = "literal-named-argument"
message = "Literal argument `'file content'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/Factory/Psr17FactoryTest.php"
code = "literal-named-argument"
message = "Literal argument `'r+'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/Factory/Psr17FactoryTest.php"
code = "literal-named-argument"
message = "Literal argument `'wfl_stream_factory'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/Factory/StreamFactoryTest.php"
code = "literal-named-argument"
message = "Literal argument `'file content'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/Factory/StreamFactoryTest.php"
code = "literal-named-argument"
message = "Literal argument `'r+'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/Factory/StreamFactoryTest.php"
code = "literal-named-argument"
message = "Literal argument `'resource content'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/Factory/StreamFactoryTest.php"
code = "literal-named-argument"
message = "Literal argument `'test'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/Factory/UploadedFileFactoryTest.php"
code = "literal-named-argument"
message = "Literal argument `'test content'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/Factory/UploadedFileFactoryTest.php"
code = "literal-named-argument"
message = "Literal argument `'test_upload'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/Factory/UploadedFileFactoryTest.php"
code = "readable-literal"
message = "Numeric literal could use underscore separators for readability."
count = 2

[[issues]]
file = "tests/src/RequestTest.php"
code = "too-many-methods"
message = "Class has too many methods."
count = 1

[[issues]]
file = "tests/src/ResponseTest.php"
code = "literal-named-argument"
message = "Literal argument `'Resource Content'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/ResponseTest.php"
code = "literal-named-argument"
message = "Literal argument `'r+'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/ResponseTest.php"
code = "readable-literal"
message = "Numeric literal could use underscore separators for readability."
count = 1

[[issues]]
file = "tests/src/ResponseTest.php"
code = "too-many-methods"
message = "Class has too many methods."
count = 1

[[issues]]
file = "tests/src/ServerRequestTest.php"
code = "excessive-parameter-list"
message = "Parameter list is too long."
count = 1

[[issues]]
file = "tests/src/ServerRequestTest.php"
code = "literal-named-argument"
message = "Literal argument `'Resource Body'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/ServerRequestTest.php"
code = "literal-named-argument"
message = "Literal argument `'r+'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/ServerRequestTest.php"
code = "literal-named-argument"
message = "Literal argument `0` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/ServerRequestTest.php"
code = "readable-literal"
message = "Numeric literal could use underscore separators for readability."
count = 2

[[issues]]
file = "tests/src/ServerRequestTest.php"
code = "too-many-methods"
message = "Class has too many methods."
count = 1

[[issues]]
file = "tests/src/StreamEdgeCaseTest.php"
code = "literal-named-argument"
message = "Literal argument `'r+'` should be passed as a named argument for clarity."
count = 7

[[issues]]
file = "tests/src/StreamTest.php"
code = "literal-named-argument"
message = "Literal argument `'File Content'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/StreamTest.php"
code = "literal-named-argument"
message = "Literal argument `'r+'` should be passed as a named argument for clarity."
count = 2

[[issues]]
file = "tests/src/StreamTest.php"
code = "literal-named-argument"
message = "Literal argument `'readonly'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/StreamTest.php"
code = "literal-named-argument"
message = "Literal argument `'w'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/StreamTest.php"
code = "literal-named-argument"
message = "Literal argument `'wfl_stream_test'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/StreamTest.php"
code = "literal-named-argument"
message = "Literal argument `'write_only'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/StreamTest.php"
code = "literal-named-argument"
message = "Literal argument `'writeonly'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/StreamTest.php"
code = "literal-named-argument"
message = "Literal argument `'writeonly_contents'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/StreamTest.php"
code = "readable-literal"
message = "Numeric literal could use underscore separators for readability."
count = 1

[[issues]]
file = "tests/src/StreamTest.php"
code = "too-many-methods"
message = "Class has too many methods."
count = 1

[[issues]]
file = "tests/src/UploadedFileEdgeCaseTest.php"
code = "literal-named-argument"
message = "Literal argument `'waffle_test_'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/UploadedFileEdgeCaseTest.php"
code = "no-error-control-operator"
message = "Unsafe use of error control operator `@`."
count = 4

[[issues]]
file = "tests/src/UploadedFileTest.php"
code = "literal-named-argument"
message = "Literal argument `'Test content'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/UploadedFileTest.php"
code = "literal-named-argument"
message = "Literal argument `'wfl_dest'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/UploadedFileTest.php"
code = "literal-named-argument"
message = "Literal argument `'wfl_dest_test'` should be passed as a named argument for clarity."
count = 3

[[issues]]
file = "tests/src/UploadedFileTest.php"
code = "literal-named-argument"
message = "Literal argument `'wfl_dest_test_2'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/UploadedFileTest.php"
code = "literal-named-argument"
message = "Literal argument `'wfl_upload_test'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/UriTest.php"
code = "readable-literal"
message = "Numeric literal could use underscore separators for readability."
count = 1

[[issues]]
file = "tests/src/UriTest.php"
code = "too-many-methods"
message = "Class has too many methods."
count = 1
