variant = "loose"

[[issues]]
file = "src/Abstract/AbstractMessage.php"
code = "impossible-condition"
message = "This condition (type `false`) will always evaluate to false."
count = 1

[[issues]]
file = "src/Abstract/AbstractMessage.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #1 of `Waffle\Commons\Http\Abstract\AbstractMessage::normalizeheadervalue`: expected `array<array-key, string>|string`, but found `mixed`.'
count = 1

[[issues]]
file = "src/Abstract/AbstractMessage.php"
code = "mixed-assignment"
message = "Assigning `mixed` type to a variable may lead to unexpected behavior."
count = 1

[[issues]]
file = "src/Emitter/ResponseEmitter.php"
code = "less-specific-argument"
message = 'Argument type mismatch for argument #1 of `Waffle\Commons\Http\Emitter\ResponseEmitter::emitheaders`: expected `array<string, array<array-key, string>>`, but provided type `array<array-key, array<array-key, string>>` is less specific.'
count = 1

[[issues]]
file = "src/Emitter/ResponseEmitter.php"
code = "missing-override-attribute"
message = 'Missing `#[Override]` attribute on overriding method `Waffle\Commons\Http\Emitter\ResponseEmitter::emit`.'
count = 1

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "invalid-return-statement"
message = 'Invalid return type for function `waffle\commons\http\factory\globalsfactory::getheadersfromglobals`: expected `array<string, string>`, but found `array<string, bool|float|non-empty-list<string>|positive-int|string>`.'
count = 1

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "less-specific-return-statement"
message = 'Returned type `array<array-key, mixed>` is less specific than the declared return type `array<string, Psr\Http\Message\UploadedFileInterface>` for function `waffle\commons\http\factory\globalsfactory::createuploadedfilesfromglobals`.'
count = 1

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "mixed-argument"
message = "Invalid argument type for argument #1 of `array_keys`: expected `array<('K.array_keys() extends array-key), ('V.array_keys() extends mixed)>`, but found `mixed`."
count = 1

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #1 of `waffle\commons\http\stream::__construct`: expected `resource|string`, but found `mixed`.'
count = 1

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #1 of `waffle\commons\http\uploadedfile::__construct`: expected `string`, but found `mixed`.'
count = 1

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "mixed-argument"
message = "Invalid argument type for argument #2 of `explode`: expected `string`, but found `nonnull`."
count = 1

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #3 of `Waffle\Commons\Http\Factory\GlobalsFactory::getparsedbody`: expected `Psr\Http\Message\StreamInterface`, but found `mixed`.'
count = 1

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #4 of `waffle\commons\http\serverrequest::__construct`: expected `Psr\Http\Message\StreamInterface|null|resource|string`, but found `mixed`.'
count = 1

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #4 of `waffle\commons\http\uploadedfile::__construct`: expected `null|string`, but found `mixed`.'
count = 1

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #5 of `waffle\commons\http\uploadedfile::__construct`: expected `null|string`, but found `mixed`.'
count = 1

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "mixed-array-access"
message = "Unsafe array access on type `mixed`."
count = 1

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "mixed-assignment"
message = "Assigning `mixed` type to a variable may lead to unexpected behavior."
count = 3

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "mixed-assignment"
message = "Assigning `nonnull` type to a variable may lead to unexpected behavior."
count = 1

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "mixed-return-statement"
message = 'Could not infer a precise return type for function `waffle\commons\http\factory\globalsfactory::getparsedbody`. Saw type `mixed`.'
count = 1

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "redundant-condition"
message = "This condition (type `true`) will always evaluate to true."
count = 1

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "redundant-null-coalesce"
message = "Redundant null coalesce: left-hand side can never be `null` or undefined."
count = 1

[[issues]]
file = "src/Factory/GlobalsFactory.php"
code = "reference-to-undefined-variable"
message = "Reference created from a previously undefined variable `$matches`."
count = 1

[[issues]]
file = "src/Factory/StreamFactory.php"
code = "mixed-argument"
message = "Invalid argument type for argument #1 of `fseek`: expected `resource`, but found `mixed`."
count = 1

[[issues]]
file = "src/Factory/StreamFactory.php"
code = "mixed-argument"
message = "Invalid argument type for argument #1 of `fwrite`: expected `resource`, but found `mixed`."
count = 1

[[issues]]
file = "src/Factory/StreamFactory.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #1 of `waffle\commons\http\stream::__construct`: expected `resource|string`, but found `mixed`.'
count = 1

[[issues]]
file = "src/Factory/StreamFactory.php"
code = "mixed-assignment"
message = "Assigning `mixed` type to a variable may lead to unexpected behavior."
count = 1

[[issues]]
file = "src/Request.php"
code = "possibly-null-operand"
message = "Possibly null right operand used in string concatenation (type `int|null`)."
count = 1

[[issues]]
file = "src/ServerRequest.php"
code = "impossible-condition"
message = "This condition (type `false`) will always evaluate to false."
count = 1

[[issues]]
file = "src/ServerRequest.php"
code = "redundant-comparison"
message = "Redundant `!==` comparison: left-hand side is never identical to (always false for !==) right-hand side."
count = 1

[[issues]]
file = "src/ServerRequest.php"
code = "redundant-logical-operation"
message = "Redundant `&&` operation: left operand is evaluated and right operand is always falsy."
count = 1

[[issues]]
file = "src/Stream.php"
code = "less-specific-nested-argument-type"
message = "Argument type mismatch for argument #2 of `clearstatcache`: expected `string`, but provided type `array<array-key, mixed>|mixed` is less specific."
count = 1

[[issues]]
file = "src/Stream.php"
code = "mixed-argument"
message = "Invalid argument type for argument #2 of `preg_match`: expected `string`, but found `nonnull`."
count = 2

[[issues]]
file = "src/Stream.php"
code = "mixed-assignment"
message = "Assigning `nonnull` type to a variable may lead to unexpected behavior."
count = 2

[[issues]]
file = "src/Stream.php"
code = "mixed-return-statement"
message = 'Could not infer a precise return type for function `waffle\commons\http\stream::getmetadata`. Saw type `mixed`.'
count = 2

[[issues]]
file = "src/Stream.php"
code = "mixed-return-statement"
message = 'Could not infer a precise return type for function `waffle\commons\http\stream::getsize`. Saw type `mixed`.'
count = 1

[[issues]]
file = "src/Stream.php"
code = "mixed-return-statement"
message = 'Could not infer a precise return type for function `waffle\commons\http\stream::isseekable`. Saw type `nonnull`.'
count = 1

[[issues]]
file = "src/Uri.php"
code = "invalid-return-statement"
message = 'Invalid return type for function `waffle\commons\http\uri::filterpath`: expected `string`, but found `null|string`.'
count = 1

[[issues]]
file = "src/Uri.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #1 of `Waffle\Commons\Http\Uri::filterfragment`: expected `string`, but found `nonnull`.'
count = 1

[[issues]]
file = "src/Uri.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #1 of `Waffle\Commons\Http\Uri::filterhost`: expected `string`, but found `nonnull`.'
count = 1

[[issues]]
file = "src/Uri.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #1 of `Waffle\Commons\Http\Uri::filterpath`: expected `string`, but found `nonnull`.'
count = 1

[[issues]]
file = "src/Uri.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #1 of `Waffle\Commons\Http\Uri::filterport`: expected `int|null`, but found `nonnull`.'
count = 1

[[issues]]
file = "src/Uri.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #1 of `Waffle\Commons\Http\Uri::filterquery`: expected `string`, but found `nonnull`.'
count = 1

[[issues]]
file = "src/Uri.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #1 of `Waffle\Commons\Http\Uri::filterscheme`: expected `string`, but found `nonnull`.'
count = 1

[[issues]]
file = "src/Uri.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #1 of `Waffle\Commons\Http\Uri::filteruserinfo`: expected `string`, but found `nonnull`.'
count = 1

[[issues]]
file = "src/Uri.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #2 of `Waffle\Commons\Http\Uri::filteruserinfo`: expected `null|string`, but found `mixed`.'
count = 1

[[issues]]
file = "src/Uri.php"
code = "nullable-return-statement"
message = 'Function `waffle\commons\http\uri::filterpath` is declared to return `string` but possibly returns a nullable value (inferred as `null|string`).'
count = 1

[[issues]]
file = "src/Uri.php"
code = "possibly-invalid-argument"
message = 'Possible argument type mismatch for argument #1 of `Waffle\Commons\Http\Uri::applyparts`: expected `array<array-key, mixed>`, but possibly received `array<array-key, mixed>|int|null|string`.'
count = 1

[[issues]]
file = "src/Uri.php"
code = "possibly-null-argument"
message = "Argument #1 of function `ltrim` is possibly `null`, but parameter type `string` does not accept it."
count = 2

[[issues]]
file = "src/Uri.php"
code = "possibly-null-argument"
message = "Argument #1 of function `str_starts_with` is possibly `null`, but parameter type `string` does not accept it."
count = 1

[[issues]]
file = "src/Uri.php"
code = "possibly-null-argument"
message = 'Argument #1 of method `Waffle\Commons\Http\Uri::applyparts` is possibly `null`, but parameter type `array<array-key, mixed>` does not accept it.'
count = 1

[[issues]]
file = "src/Uri.php"
code = "possibly-null-operand"
message = "Possibly null right operand used in string concatenation (type `non-empty-string|null`)."
count = 1

[[issues]]
file = "tests/bootstrap.php"
code = "mixed-assignment"
message = "Assigning `mixed` type to a variable may lead to unexpected behavior."
count = 1

[[issues]]
file = "tests/src/Abstract/AbstractMessageTest.php"
code = "mixed-assignment"
message = "Assigning `mixed` type to a variable may lead to unexpected behavior."
count = 8

[[issues]]
file = "tests/src/Abstract/AbstractMessageTest.php"
code = "mixed-method-access"
message = "Attempting to access a method on a non-object type (`mixed`)."
count = 21

[[issues]]
file = "tests/src/Emitter/ResponseEmitterTest.php"
code = "mixed-return-statement"
message = 'Could not infer a precise return type for function `waffle\commons\http\emitter\headers_sent`. Saw type `nonnull`.'
count = 1

[[issues]]
file = "tests/src/Factory/GlobalsFactoryTest.php"
code = "possibly-false-argument"
message = "Argument #1 of function `file_put_contents` is possibly `false`, but parameter type `string` does not accept it."
count = 2

[[issues]]
file = "tests/src/Factory/GlobalsFactoryTest.php"
code = "possibly-false-argument"
message = "Argument #1 of function `unlink` is possibly `false`, but parameter type `string` does not accept it."
count = 2

[[issues]]
file = "tests/src/Factory/Psr17FactoryTest.php"
code = "possibly-false-argument"
message = "Argument #1 of function `file_put_contents` is possibly `false`, but parameter type `string` does not accept it."
count = 1

[[issues]]
file = "tests/src/Factory/Psr17FactoryTest.php"
code = "possibly-false-argument"
message = "Argument #1 of function `unlink` is possibly `false`, but parameter type `string` does not accept it."
count = 1

[[issues]]
file = "tests/src/Factory/Psr17FactoryTest.php"
code = "possibly-false-argument"
message = 'Argument #1 of method `Waffle\Commons\Http\Factory\StreamFactory::createstreamfromfile` is possibly `false`, but parameter type `string` does not accept it.'
count = 1

[[issues]]
file = "tests/src/Factory/StreamFactoryTest.php"
code = "missing-override-attribute"
message = 'Missing `#[Override]` attribute on overriding method `Waffle\Commons\Http\Factory\StreamFactoryTest::tearDown`.'
count = 1

[[issues]]
file = "tests/src/Factory/StreamFactoryTest.php"
code = "possibly-false-argument"
message = "Argument #1 of function `file_put_contents` is possibly `false`, but parameter type `string` does not accept it."
count = 1

[[issues]]
file = "tests/src/Factory/StreamFactoryTest.php"
code = "possibly-false-argument"
message = "Argument #1 of function `unlink` is possibly `false`, but parameter type `string` does not accept it."
count = 1

[[issues]]
file = "tests/src/Factory/StreamFactoryTest.php"
code = "possibly-false-argument"
message = 'Argument #1 of method `Waffle\Commons\Http\Factory\StreamFactory::createstreamfromfile` is possibly `false`, but parameter type `string` does not accept it.'
count = 1

[[issues]]
file = "tests/src/Factory/UploadedFileFactoryTest.php"
code = "possibly-false-argument"
message = "Argument #1 of function `file_put_contents` is possibly `false`, but parameter type `string` does not accept it."
count = 1

[[issues]]
file = "tests/src/Factory/UploadedFileFactoryTest.php"
code = "possibly-false-argument"
message = "Argument #1 of function `unlink` is possibly `false`, but parameter type `string` does not accept it."
count = 1

[[issues]]
file = "tests/src/ResponseTest.php"
code = "invalid-argument"
message = 'Invalid argument type for argument #3 of `waffle\commons\http\response::__construct`: expected `Psr\Http\Message\StreamInterface|null|resource|string`, but found `int(12345)`.'
count = 1

[[issues]]
file = "tests/src/ServerRequestTest.php"
code = "invalid-argument"
message = 'Invalid argument type for argument #1 of `Waffle\Commons\Http\ServerRequest::withparsedbody`: expected `array<array-key, mixed>|null|object`, but found `int(123)`.'
count = 1

[[issues]]
file = "tests/src/ServerRequestTest.php"
code = "invalid-argument"
message = 'Invalid argument type for argument #4 of `waffle\commons\http\serverrequest::__construct`: expected `Psr\Http\Message\StreamInterface|null|resource|string`, but found `int(12345)`.'
count = 1

[[issues]]
file = "tests/src/ServerRequestTest.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #9 of `waffle\commons\http\serverrequest::__construct`: expected `array<array-key, mixed>|null|object`, but found `mixed`.'
count = 1

[[issues]]
file = "tests/src/StreamTest.php"
code = "invalid-argument"
message = 'Invalid argument type for argument #1 of `waffle\commons\http\stream::__construct`: expected `resource|string`, but found `int(12345)`.'
count = 1

[[issues]]
file = "tests/src/StreamTest.php"
code = "mixed-argument"
message = "Invalid argument type for argument #1 of `fread`: expected `resource`, but found `mixed`."
count = 1

[[issues]]
file = "tests/src/StreamTest.php"
code = "mixed-argument"
message = "Invalid argument type for argument #1 of `fseek`: expected `resource`, but found `mixed`."
count = 1

[[issues]]
file = "tests/src/StreamTest.php"
code = "mixed-argument"
message = "Invalid argument type for argument #1 of `ftell`: expected `resource`, but found `mixed`."
count = 1

[[issues]]
file = "tests/src/StreamTest.php"
code = "mixed-argument"
message = "Invalid argument type for argument #1 of `fwrite`: expected `resource`, but found `mixed`."
count = 1

[[issues]]
file = "tests/src/StreamTest.php"
code = "mixed-argument"
message = "Invalid argument type for argument #1 of `stream_get_contents`: expected `resource`, but found `mixed`."
count = 1

[[issues]]
file = "tests/src/StreamTest.php"
code = "possibly-false-argument"
message = "Argument #1 of function `file_put_contents` is possibly `false`, but parameter type `string` does not accept it."
count = 1

[[issues]]
file = "tests/src/StreamTest.php"
code = "possibly-false-argument"
message = "Argument #1 of function `unlink` is possibly `false`, but parameter type `string` does not accept it."
count = 5

[[issues]]
file = "tests/src/StreamTest.php"
code = "possibly-false-argument"
message = 'Argument #1 of method `waffle\commons\http\stream::__construct` is possibly `false`, but parameter type `resource|string` does not accept it.'
count = 5

[[issues]]
file = "tests/src/UploadedFileEdgeCaseTest.php"
code = "invalid-argument"
message = '''Invalid argument type for argument #1 of `waffle\commons\http\uploadedfile::__construct`: expected `string`, but found `list{string('not a string')}`.'''
count = 1

[[issues]]
file = "tests/src/UploadedFileEdgeCaseTest.php"
code = "invalid-property-assignment-value"
message = "Invalid type for property `$tempFile`: expected `string`, but got `false|string`."
count = 1

[[issues]]
file = "tests/src/UploadedFileEdgeCaseTest.php"
code = "missing-override-attribute"
message = 'Missing `#[Override]` attribute on overriding method `WaffleTests\Commons\Http\UploadedFileEdgeCaseTest::setUp`.'
count = 1

[[issues]]
file = "tests/src/UploadedFileEdgeCaseTest.php"
code = "missing-override-attribute"
message = 'Missing `#[Override]` attribute on overriding method `WaffleTests\Commons\Http\UploadedFileEdgeCaseTest::tearDown`.'
count = 1

[[issues]]
file = "tests/src/UploadedFileTest.php"
code = "impossible-condition"
message = "This condition (type `false`) will always evaluate to false."
count = 1

[[issues]]
file = "tests/src/UploadedFileTest.php"
code = "invalid-property-assignment-value"
message = "Invalid type for property `$tempFile`: expected `string`, but got `false|string`."
count = 1

[[issues]]
file = "tests/src/UploadedFileTest.php"
code = "mixed-argument"
message = "Invalid argument type for argument #3 of `rename`: expected `null|resource`, but found `mixed`."
count = 1

[[issues]]
file = "tests/src/UploadedFileTest.php"
code = "possibly-false-argument"
message = "Argument #1 of function `file_get_contents` is possibly `false`, but parameter type `string` does not accept it."
count = 1

[[issues]]
file = "tests/src/UploadedFileTest.php"
code = "possibly-false-argument"
message = "Argument #1 of function `unlink` is possibly `false`, but parameter type `string` does not accept it."
count = 3

[[issues]]
file = "tests/src/UploadedFileTest.php"
code = "possibly-false-argument"
message = 'Argument #1 of method `Waffle\Commons\Http\UploadedFile::moveto` is possibly `false`, but parameter type `string` does not accept it.'
count = 5

[[issues]]
file = "tests/src/UploadedFileTest.php"
code = "possibly-false-argument"
message = 'Argument #1 of method `phpunit\framework\assert::assertfileexists` is possibly `false`, but parameter type `string` does not accept it.'
count = 1

[[issues]]
file = "tests/src/UploadedFileTest.php"
code = "redundant-comparison"
message = "Redundant `===` comparison: left-hand side is never identical to right-hand side."
count = 1
